tuanlq11:
  token:
    secret:         BupsNIvC$YE00495anfYz32&f19km43ymJ83b!ilT6tNgk5hNzFZKV&a$vqOEkdlA5ZfrS252flphjsIyusWbO7GTX%$v6c3rePR
    secret_cipher:  drEKTSaP&qENe3pEP&*JQfh3hqTLovDEIuvD#CuZ#A6Iuh4NmYljEW$HEGSfVcBJlUsTOWWFU5H&fT@w^i9wiM7lr*TUm4*Grc6T
    alg:            HS256
    identify:       email
    ttl:            300
    ttl_blacklist:  86400
    encrypt:        true
    error_code:     1